name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12.8
      uses: actions/setup-python@v5
      with:
        python-version: '3.12.8'
    - name: Install Black
      run: pip install black
    - name: Apply Black formatting
      run: black .
    - name: Commit formatting changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add -A
        git commit -m "Apply Black formatting" || echo "No changes to commit"

  lint:
    needs: format
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12.8
      uses: actions/setup-python@v5
      with:
        python-version: '3.12.8'
    - name: Install Ruff
      run: pip install ruff
    - name: Run Ruff linting
      run: ruff check .

  typecheck:
    needs: format
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12.8
      uses: actions/setup-python@v5
      with:
        python-version: '3.12.8'
    - name: Install mypy
      run: pip install mypy
    - name: Run type checks
      run: mypy .
